server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-218-171-44.compute-1.amazonaws.com:5432/dd2d5mgspt4nau
    username: gxcsqnrzhiwzlt
    password: a4bf8bf5d2131996a0b1e16c0f31b4a6629f3013c5eb2663ef16179cd33b590a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: furqonfadlillah7@gmail
    password: jmekdmjqdqzdmgmi
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false